// lib/missions/factionMissions.ts
export const FACTION_MISSIONS = [
  {
    id: 'share_faction_cover',
    title: '🤝 APOYA A TU BANDO',
    description: 'Comparte 1 cover de un compañero del Bando',
    type: 'daily',
    requiredValue: 1,
    rewardCoins: 30,
    rewardXP: 15,
    rewardItem: 'cookie',
    color: '#00F3FF',
  },
  {
    id: 'send_faction_gift',
    title: '🎁 REGALO DE HERMANDAD',
    description: 'Envía 3 regalos de mochila a miembros de tu Bando',
    type: 'daily',
    requiredValue: 3,
    rewardCoins: 50,
    rewardXP: 25,
    rewardItem: 'coffee',
    color: '#FF69B4',
  },
  {
    id: 'duet_with_faction',
    title: '🎤 DUETO DE GUERREROS',
    description: 'Realiza 1 dueto con un miembro de tu Bando',
    type: 'weekly',
    requiredValue: 1,
    rewardCoins: 150,
    rewardXP: 75,
    rewardItem: 'pizza',
    color: '#D4AF37',
  },
  {
    id: 'invite_to_faction',
    title: '👥 CRECE EL BANDO',
    description: 'Invita a 1 amigo a unirse a tu Bando',
    type: 'weekly',
    requiredValue: 1,
    rewardCoins: 100,
    rewardXP: 50,
    rewardItem: 'cake',
    color: '#9B59B6',
  },
  {
    id: 'faction_support',
    title: '💪 APOYO COLECTIVO',
    description: 'Recibe 5 regalos de mochila de miembros de tu Bando',
    type: 'weekly',
    requiredValue: 5,
    rewardCoins: 200,
    rewardXP: 100,
    rewardItem: 'unicorn',
    color: '#FF0055',
  },
];