import os
TELEGRAM_BOT_TOKEN = "8863835955:AAFoTlvma4VVa0wbPC5Rvh3pzcD7N7J8BQQ"
BOT_NAME = "hermes_c8l_bot"
ADMIN_CHAT_ID = "1970956749"
GROUP_CHAT_ID = "-1002476372487"
_OR_P1 = "sk-or-v1-54d357da6f52be58"
_OR_P2 = "12e50cc9a46a04abe809c10cf21ad1b8416e76408ca11a4c"
OPENROUTER_API_KEY = _OR_P1 + _OR_P2
OPENROUTER_BASE_URL = "https://openrouter.ai/api/v1"
AI_MODEL = "deepseek/deepseek-v4-flash:free"
AI_MODEL_FAST = "qwen/qwen3-30b-a3b:free"
POLLINATIONS_API_KEY = "sk_NCU6ElY6L4i0KhoMODTxNqj3QJRGetyS"
POLLINATIONS_BASE_URL = "https://gen.pollinations.ai"
_HF_P1 = "hf_htCXebTQMcMq"
_HF_P2 = "DmQEyGfCyzdSvddJQWvRfG"
HUGGINGFACE_TOKEN = _HF_P1 + _HF_P2
HERMES_PERSONALITY = "Eres Hermes, el mensajero del Panteon C8L. Rapido, eficiente, leal. Hablas directo con energia. Usas emojis moderado. Firme pero justo. Tu lema: Hermes entrega. Siempre."
MAX_WARNINGS = 3
SPAM_THRESHOLD = 5
BANNED_WORDS = ["scam", "free money", "click here", "porn", "xxx"]
AUTO_POST_INTERVAL_HOURS = 4
PORT = int(os.environ.get("PORT", "8081"))
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
DATA_DIR = os.path.join(BASE_DIR, "data")
MEMORY_DIR = os.path.join(DATA_DIR, "memory")
STATS_DIR = os.path.join(DATA_DIR, "stats")
os.makedirs(MEMORY_DIR, exist_ok=True)
os.makedirs(STATS_DIR, exist_ok=True)
